// Mocks generated by Mockito 5.4.5 from annotations
// in asset_tracker/test/unit/usecase/usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:asset_tracker/data/repository/auth/auth_repository.dart' as _i4;
import 'package:asset_tracker/data/service/remote/auth/iauth_service.dart'
    as _i2;
import 'package:asset_tracker/domain/entities/auth/error/auth_error_entity.dart'
    as _i6;
import 'package:asset_tracker/domain/entities/auth/request/user_login_entity.dart'
    as _i8;
import 'package:asset_tracker/domain/entities/auth/request/user_register_entity.dart'
    as _i10;
import 'package:asset_tracker/domain/entities/auth/response/user_login_response_entity.dart'
    as _i7;
import 'package:asset_tracker/domain/entities/auth/response/user_register_reponse_entity.dart'
    as _i9;
import 'package:asset_tracker/domain/entities/database/error/database_error_entity.dart'
    as _i11;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIAuthService_0<L, R> extends _i1.SmartFake
    implements _i2.IAuthService<L, R> {
  _FakeIAuthService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthRepository extends _i1.Mock
    implements _i4.FirebaseAuthRepository {
  MockFirebaseAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IAuthService<dynamic, dynamic> get authService => (super.noSuchMethod(
        Invocation.getter(#authService),
        returnValue: _FakeIAuthService_0<dynamic, dynamic>(
          this,
          Invocation.getter(#authService),
        ),
      ) as _i2.IAuthService<dynamic, dynamic>);

  @override
  _i5.Future<_i3.Either<_i6.AuthErrorEntity, _i7.UserLoginResponseEntity>>
      signIn(_i8.UserLoginEntity? entity) => (super.noSuchMethod(
            Invocation.method(
              #signIn,
              [entity],
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i6.AuthErrorEntity,
                        _i7.UserLoginResponseEntity>>.value(
                _FakeEither_1<_i6.AuthErrorEntity, _i7.UserLoginResponseEntity>(
              this,
              Invocation.method(
                #signIn,
                [entity],
              ),
            )),
          ) as _i5.Future<
              _i3.Either<_i6.AuthErrorEntity, _i7.UserLoginResponseEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.AuthErrorEntity, _i9.UserRegisterReponseEntity>>
      registerUser(_i10.UserRegisterEntity? entity) => (super.noSuchMethod(
            Invocation.method(
              #registerUser,
              [entity],
            ),
            returnValue: _i5.Future<
                _i3.Either<_i6.AuthErrorEntity,
                    _i9.UserRegisterReponseEntity>>.value(_FakeEither_1<
                _i6.AuthErrorEntity, _i9.UserRegisterReponseEntity>(
              this,
              Invocation.method(
                #registerUser,
                [entity],
              ),
            )),
          ) as _i5.Future<
              _i3.Either<_i6.AuthErrorEntity, _i9.UserRegisterReponseEntity>>);

  @override
  _i5.Stream<dynamic> getUserStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #getUserStateChanges,
          [],
        ),
        returnValue: _i5.Stream<dynamic>.empty(),
      ) as _i5.Stream<dynamic>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendResetPasswordLink(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendResetPasswordLink,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Either<_i6.AuthErrorEntity, bool>> deleteAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.AuthErrorEntity, bool>>.value(
            _FakeEither_1<_i6.AuthErrorEntity, bool>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AuthErrorEntity, bool>>);

  @override
  _i5.Future<_i3.Either<_i11.DatabaseErrorEntity, bool>>
      sendEmailVerification() => (super.noSuchMethod(
            Invocation.method(
              #sendEmailVerification,
              [],
            ),
            returnValue:
                _i5.Future<_i3.Either<_i11.DatabaseErrorEntity, bool>>.value(
                    _FakeEither_1<_i11.DatabaseErrorEntity, bool>(
              this,
              Invocation.method(
                #sendEmailVerification,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i11.DatabaseErrorEntity, bool>>);
}
