import 'package:asset_tracker/core/config/localization/generated/locale_keys.g.dart';

enum DashboardFilterEnum {
  ALL(LocaleKeys.dashboard_filterAll),
  GOLD(LocaleKeys.dashboard_filterGold),
  FOREIGN_CURRENCY(LocaleKeys.dashboard_filterForeignCurrency),
  PRECIOUS_METAL(LocaleKeys.dashboard_filterPreciousMetal);

  final String name;
  const DashboardFilterEnum(this.name);
}

final Map<String, DashboardFilterEnum> currencyTypes = {
  "altin": DashboardFilterEnum.GOLD,
  "ayar14": DashboardFilterEnum.GOLD,
  "ayar22": DashboardFilterEnum.GOLD,
  "kulcealtin": DashboardFilterEnum.GOLD,
  "gramaltin": DashboardFilterEnum.GOLD,
  "ceyrek_yeni": DashboardFilterEnum.GOLD,
  "ceyrek_eski": DashboardFilterEnum.GOLD,
  "yarim_yeni": DashboardFilterEnum.GOLD,
  "yarim_eski": DashboardFilterEnum.GOLD,
  "tek_yeni": DashboardFilterEnum.GOLD,
  "tek_eski": DashboardFilterEnum.GOLD,
  "ata_yeni": DashboardFilterEnum.GOLD,
  "ata_eski": DashboardFilterEnum.GOLD,
  "ata5_yeni": DashboardFilterEnum.GOLD,
  "ata5_eski": DashboardFilterEnum.GOLD,
  "gremese_yeni": DashboardFilterEnum.GOLD,
  "gremese_eski": DashboardFilterEnum.GOLD,
  "ons": DashboardFilterEnum.GOLD,
  "usdpure": DashboardFilterEnum.GOLD,
  "xauusd": DashboardFilterEnum.GOLD,
  "xauxag": DashboardFilterEnum.GOLD,
  "usdtry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "eurtry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "gbptry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "chftry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "cadtry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "sartry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "jpytry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "dkktry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "plntry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "huftry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "sektry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "zartry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "audtry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "noktry": DashboardFilterEnum.FOREIGN_CURRENCY,
  "audusd": DashboardFilterEnum.FOREIGN_CURRENCY,
  "gbpusd": DashboardFilterEnum.FOREIGN_CURRENCY,
  "usdjpy": DashboardFilterEnum.FOREIGN_CURRENCY,
  "usdchf": DashboardFilterEnum.FOREIGN_CURRENCY,
  "usdcad": DashboardFilterEnum.FOREIGN_CURRENCY,
  "eurusd": DashboardFilterEnum.FOREIGN_CURRENCY,
  "usdsar": DashboardFilterEnum.FOREIGN_CURRENCY,
  "usdkg": DashboardFilterEnum.FOREIGN_CURRENCY,
  "eurkg": DashboardFilterEnum.FOREIGN_CURRENCY,
  "xagusd": DashboardFilterEnum.FOREIGN_CURRENCY,
  "xptusd": DashboardFilterEnum.FOREIGN_CURRENCY,
  "xpdusd": DashboardFilterEnum.FOREIGN_CURRENCY,
  "gumustry": DashboardFilterEnum.PRECIOUS_METAL,
  "gumususd": DashboardFilterEnum.PRECIOUS_METAL,
  "platin": DashboardFilterEnum.PRECIOUS_METAL,
  "paladyum": DashboardFilterEnum.PRECIOUS_METAL,
};
