name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Flutter SDK setup
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
          channel: 'stable'
          architecture: 'x64'
          cache: true
   
      # Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-sdk-${{ runner.os }}-flutter-${{ steps.flutter-action.outputs.cache-key }}
          restore-keys: |
            flutter-sdk-${{ runner.os }}-flutter-
      
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Cache Pub packages
      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: /home/runner/.pub-cache
          key: pub-cache-${{ runner.os }}-flutter-${{ steps.flutter-action.outputs.cache-key }}-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-flutter-

      # Kod formatını kontrol eder (opsiyonel)
      #- name: Verify formatting
        #run: flutter pub run dart_style:format --dry-run --set-exit-if-changed .

      # Kod analizini yapar
      - name: Analyze project source
        run: flutter analyze

      # Testleri çalıştırır
      - name: Run tests
        run: flutter test
